# Generated by Django 4.2.7 on 2023-11-25 16:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('gdrive', '0002_downloading'),
    ]

    operations = [
        migrations.AddField(
            model_name='downloading',
            name='filename',
            field=models.CharField(blank=True, max_length=1000),
        ),
        migrations.AlterField(
            model_name='drivemodel',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='driveModel', to=settings.AUTH_USER_MODEL),
        ),
    ]
