# Generated by Django 4.2.7 on 2023-11-26 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gdrive', '0003_downloading_filename_alter_drivemodel_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='downloading',
            name='status',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
