# Generated by Django 4.2.7 on 2023-12-02 10:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("gdrive", "0004_downloading_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="downloading",
            name="downloaded_thread",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="downloading",
            name="location",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="downloading",
            name="size",
            field=models.TextField(blank=True),
        ),
    ]
